layout = [
    ["weather", "weather", "weather", "weather", "weather", "weather"],
    ["weather", "weather", "weather", "weather", "weather", "weather"],
    ["latency", "latency", "latency", "status", "status", "status"]
]

[views.latency]
update_interval = 500
target_host = "www.google.com"

[views.status]
update_interval = 10000

[views.weather]
update_interval = 600000
owm_language = "en"
owm_unit = "metric"